algoritmo "idade"
var
   anoAtual, anoNasc, idade: Inteiro
inicio
      Escreva("Em que ano estamos? ")
      Leia(anoAtual)
      Escreva("Escreva o ano de nascimento: ")
      Leia(anoNasc)
      idade <- anoAtual-anoNasc)
      Escreval("A idade é ",idade," anos!")
      Se (idade > 18) Entao
      Escreval("Você já é maior de idade!")
      senao
      Escreval("Você ainda é menor de idade!")
      fimSe
fimalgoritmo